### ISSUE TITLE
what is require"fs"?

### ISSUE THREAD

**Issue by pallaviMN** [indooorsman/node-json-watch#1]
Can you please tell us how to install fs ?

**Comment by indooorsman** [comment]
it's a nodejs module 
if you have nodejs installed, there's no need to install 'fs' ....
see more: https://nodejs.org/dist/latest-v6.x/docs/api/fs.html

**Comment by pallaviMN** [comment]
i have not installed node.js, can you please tell me how to install fs.js? is it HTML file or javascript?

**Comment by pallaviMN** [comment]
node js is installed & require.js is installed, but getting error as
 fs.js:4 Uncaught ReferenceError: require is not defined

**Comment by indooorsman** [comment]
this is a nodejs application, cannot run in the browser

2016年7月29日 18:05，"pallaviMN" notifications@github.com写道：

node js is installed & require.js is installed, but getting error as
fs.js:4 Uncaught ReferenceError: require is not defined

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
https://github.com/indooorsman/node-json-watch/issues/1#issuecomment-236143450,
or mute the thread

**Comment by pallaviMN** [comment]
Should i try in any android device?

**Comment by indooorsman** [comment]
no… can only run on server side

2016年7月29日 18:09，"pallaviMN" notifications@github.com写道：

**Comment by pallaviMN** [comment]
So it cant be used for check file changes in android external root directory right?

**Comment by indooorsman** [comment]
right,  it cant

2016年7月29日 18:30，"pallaviMN" notifications@github.com写道：
